### ISSUE TITLE
Path suggestion

### ISSUE THREAD

**Issue by instance-id** [MacacaGames/OnionDataEditor#1]
Hey there,
    I wanted to check this package out, but as an asset imported into my Assets folder to be able to look at the code a bit more easily but due to how the path was coded, it gave some errors when I didn't have it in the root directory. I came up with this solution that seems to work pretty well in case you were interested in it. 
```cs
// -- OnionDataEditor.cs
const string RootPath = "OnionDataEditor";
const string ResourcePath = "OnionDataEditorResource";
const string AsmdefPath = "t:ASMDEF OnionDataEditor.Editor";

public static string Path
{
    get
    {
        var asmdefPath = GetAsmdefPath();
        return asmdefPath != string.Empty ? asmdefPath : "Packages/com.macacagames.oniondataeditor/";
    }
}

public static string GetAsmdefPath()
{
    var p = Directory.GetParent(AssetDatabase.FindAssets(AsmdefPath)
        .Select(AssetDatabase.GUIDToAssetPath)
        .FirstOrDefault() ?? string.Empty)?.Parent?.ToString();

    if (p.StartsWith(Application.dataPath)) {
        return  "Assets" + p.Substring(Application.dataPath.Length);
    }
    return string.Empty;
}

```

I like the interface you came up with, and how the QueryableData works. It is making me want to rethink how I went about obtaining data in some of my own tools now, lol. :+1: 

Thanks,

**Comment by ttesttes93405** [comment]
Thanks for your solution. It is a good idea to use `AssetDatabase.FindAssets`.
I've fixed this issue in `1.0.1`.
